######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 13 22:34:28 2014
######################################################################

CONFIG += qwt
TEMPLATE = lib
#TARGET = QuickPlot.so
TARGET = QuickPlot
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QuickPlot.h
SOURCES += QuickPlot.cpp
